server:
  port: 8088  # 端口

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdb-3gp95vf2.cd.tencentcdb.com:10064/student?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: ljj1314()
    hikari:
      maximum-pool-size: 12 #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      connection-timeout: 60000  #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      minimum-idle: 10  #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      idle-timeout: 500000  #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      max-lifetime: 540000  #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短

  thymeleaf:
    cache: false
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入

mybatis:
  mapperLocations: classpath:mapper/*.xml
  #  实体类的包名
  typeAliasesPackage: student.pojo
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句

